/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;


import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test() throws IOException {

        try {
            Reader reader = Files.newBufferedReader(Paths.get("C:/Users/peter/quotes/app/src/main/java/quotes/gson/recentquotes.json"));
            Gson gson = new Gson();
            List<Quotes> users = new Gson().fromJson(reader, new TypeToken<List<Quotes>>() {}.getType());

            assertEquals("Marilyn Monroe", users.get(0).getAuthor());
            assertEquals("“I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.”", users.get(0).getText());

        }catch (Exception ex){
            ex.printStackTrace();
        }
    }

    @Test public void FileToStringAndParsTest() throws IOException {

    }
}
